version: "3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    build:
      context: image
      dockerfile: Dockerfile
      args:
        - ENABLED_MODULES=subs-filter
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
