version: "3"

services:
  reverse:
    container_name: reverse
    restart: always
    hostname: reverse
    build:
      context: image
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - UNGUESS_URL=https://dev.unguess.io
